[graph]
all-features = true

[advisories]
ignore = []

[bans]
allow-wildcard-paths = true
multiple-versions = "allow"
wildcards = "deny"

[licenses]
allow = ["Apache-2.0", "BSD-3-Clause", "ISC", "MIT", "MPL-2.0", "Unicode-3.0"]
confidence-threshold = 1.0

[licenses.private]
ignore = true

[sources]
unknown-git = "deny"
unknown-registry = "deny"
